### ISSUE TITLE
Update the weight and percent form inputs to be number inputs

### ISSUE THREAD

**Issue by tarikhamilton** [tarikhamilton/one-rep-max#3]
Create a `NumberInput` component. `TextInput` and `NumberInput` should share styles. Make `NumberInput` and `TextInput` be wrappers for `Input` but with different types.

**Comment by ielixirz** [comment]
hi can I have a quick work on this thanks

**Comment by tarikhamilton** [comment]
> hi can I have a quick work on this thanks

Yes! Go for it :)

**Comment by ielixirz** [comment]
pr opened https://github.com/tarikhamilton/one-rep-max/pull/5

could you check and if there is anything still you need me to fix or change feel free to tell me thanks!
